---

name: Test Gaia Upgrade Using Stateful Archive (v8 to v9)
on:
  workflow_dispatch:
  schedule:
    # At 15:30 on Monday.
    - cron: '30 15 * * 1'
  pull_request:
    types:
      - opened
      - closed
  push:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'logs/**'
      - '!examples/inventory-local.yml'
      - 'README.md'
jobs:
  test-cosmoshub:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Bypass the grub-efi-amd64-signed package
        run: apt-mark hold grub-efi-amd64-signed
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible toml
      - name: Configure ansible.cfg
        run: echo "transport = local" >> ansible.cfg
      - name: Install ansible-galaxy requirements
        run: ansible-galaxy install -r requirements.yml
      - name: Run playbook
        run: |
          ansible-playbook node.yml -i examples/inventory-archive-upgrade-v8-v9.yml --extra-vars "target=local reboot=false chain_binary_source=release"
      - name: Check cosmovisor service
        run: systemctl status cosmovisor
      - name: Check blocks are being produced
        run: |
          height=$(curl -s https://cosmos-rpc.polkachu.com/block | jq -r '.result.block.header.height')
          echo "Waiting for block $[ $height + 100 ]..."
          tests/test_block_production.sh 127.0.0.1 26657 $[ $height + 100]
